"""add rag to conversations table and content type to documents table

Revision ID: baff9cff71dd
Revises: 3371a442b4ca
Create Date: 2026-08-16 00:00:41.692110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baff9cff71dd'
down_revision: Union[str, Sequence[str], None] = '3371a442b4ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("conversations", sa.Column("use_rag", sa.Boolean(), nullable=False, server_default=sa.true()))
    op.drop_index(op.f('ix_document_chunks_embedding_hnsw'), table_name='document_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.add_column("documents", sa.Column("content_type", sa.String(128), nullable=True))
    op.add_column("documents", sa.Column("original_content", sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'original_content')
    op.drop_column('documents', 'content_type')
    op.create_index(op.f('ix_document_chunks_embedding_hnsw'), 'document_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_column('conversations', 'use_rag')
    # ### end Alembic commands ###
